services:
    app:
        # image: store-fastify-app
        build: .
        restart: always
        expose:
            - 5000
        hostname: api_link
        command: npm run migrate:dev
        ports:
            - '5000:5000'
        networks:
            api:
        depends_on:
            - db

    db:
        image: mysql:8.2.0
        restart: unless-stopped
        env_file:
            - .env
        hostname: mysql_db
        ports:
            - 3306:3306
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - api

networks:
    api:
volumes:
    mysqldata:
